name: XMake CI

on:
   release:
      types: [published]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: "[${{ matrix.mode }}] Build on ${{ matrix.os }}-latest"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        mode: [release, rel-editor, rel-server]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XMake
        uses: xmake-io/github-action-setup-xmake@v1
        package-cache: true
        package-cache-key: ${{matrix.os}}

      - name: Configure XMake
        run: xmake f -y -m ${{ matrix.mode }}

      - name: Build with XMake
        run: xmake

      - name: Create ZIP MacOS
        if: ${{matrix.os}}==macos
        run: |
            cd build/macosx/x64/${{matrix.mode}}
            zip -r ../../../../../${{matrix.mode}}-${{matrix.os}}.zip . -x '*.lib,*.so'

      - name: Create ZIP Ubuntu
        if: ${{matrix.os}}==ubuntu
        run: |
            cd build/linux/x64/${{matrix.mode}}
            zip -r ../../../../../${{matrix.mode}}-${{matrix.os}}.zip . -x '*.lib,*.so'

      - name: Create ZIP Windows
        if: ${{matrix.os}}==windows
        run: |
            cd build/windows/x64/${{matrix.mode}}
            zip -r ../../../../../${{matrix.mode}}-${{matrix.os}}.zip . -x '*.lib,*.so'

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{matrix.mode}}-${{matrix.os}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
