name: XMake CI

on:
   release:
      types: [published]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: "[${{ matrix.mode }}] Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        mode: [release, rel-editor, rel-server]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Configure XMake
        run: xmake f -y -m ${{ matrix.mode }}

      - name: Build with XMake
        run: xmake
      - name: Create ZIP excluding .lib files
        run: |
            cd build/PLATFORM/ARCH/TARGET
            zip -r ../../../../../${{matrix.mode}}-${{matrix.os}}.zip . -x '*.lib'

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{matrix.mode}}-${{matrix.os}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
