name: XMake CI Linux

on:
    release:
        types: [published]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
    build:
        name: "[${{ matrix.mode }}] Build on ${{ matrix.os }}-latest"
        runs-on: ${{ matrix.os }}-latest
        strategy:
            matrix:
                os: [ubuntu]
                mode: [release]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup OpenGL for ubuntu
              if: matrix.os == 'ubuntu'
              run: sudo apt-get -y update && sudo apt-get install --fix-missing -y libgl1-mesa-dev mesa-utils

            - name: Install XMake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                  package-cache: true
                  package-cache-key: ${{matrix.os}}

            - name: Configure XMake
              run: xmake f -y -m ${{ matrix.mode }}

            - name: Build with XMake
              run: xmake build -a

            - name: Create ZIP Linux
              if: matrix.os == 'ubuntu'
              uses: thedoctor0/zip-release@0.7.5
              with:
                  type: 'zip'
                  filename: '../../../../${{matrix.mode}}-${{matrix.os}}.zip'
                  directory: build/linux/x86_64/${{matrix.mode}}
                  exclusions: '*.lib *.a *.dll'

            - name: Upload Release
              run: gh release upload ${{github.event.release.tag_name}} ${{matrix.mode}}-${{matrix.os}}.zip
              env:
                  GITHUB_TOKEN: ${{ github.TOKEN }}
